REQUIRED_SUBJECT_FIELDS = [
    "subject_address",
    "above_grade_sqft",
    "property_type",
    "levels",
]

OPTIONAL_SUBJECT_FIELDS = [
    "property_subtype",
    "beds",
    "baths",
    "year_built",
    "real_avm",
    "real_avm_range_low",
    "real_avm_range_high",
    "zillow_estimate",
    "redfin_estimate",
    "lot_size_sqft",
    "lot_sqft",
    "style",
    "stories",
    "subject_layout_notes",
    "basement_sqft",
    "finished_basement_sqft",
    "unfinished_basement_sqft",
    "total_finished_sqft",
    "building_area_total",
    "above_grade_source",
    "summary_building_sqft",
    "county",
    "apn",
    "clip",
    "schedule_number",
    "neighborhood_name",
    "neighborhood_code",
    "subdivision",
    "zoning",
    "school_district",
    "elementary_school",
    "middle_school",
    "high_school",
]

FIELD_LABELS = {
    "subject_address": "Subject Address",
    "above_grade_sqft": "Above Grade Finished Area",
    "property_type": "Property Type",
    "levels": "Levels",
    "property_subtype": "Property Subtype",
    "beds": "Bedrooms",
    "baths": "Bathrooms",
    "year_built": "Year Built",
    "real_avm": "RealAVM",
    "real_avm_range_low": "RealAVM Range Low",
    "real_avm_range_high": "RealAVM Range High",
    "zillow_estimate": "Zillow Estimate / Zestimate",
    "redfin_estimate": "Redfin Estimate",
    "lot_size_sqft": "Lot Size SqFt",
    "lot_sqft": "Lot SqFt",
    "style": "Style",
    "stories": "Stories",
    "subject_layout_notes": "Subject Layout Notes",
    "basement_sqft": "Total Basement SqFt",
    "finished_basement_sqft": "Finished Basement SqFt",
    "unfinished_basement_sqft": "Unfinished Basement SqFt",
    "total_finished_sqft": "Total Finished SqFt",
    "building_area_total": "Building Total SqFt",
    "above_grade_source": "Above Grade Source",
    "summary_building_sqft": "Realist Summary Bldg SqFt",
    "county": "County",
    "apn": "APN",
    "clip": "CLIP",
    "schedule_number": "Schedule Number",
    "neighborhood_name": "Neighborhood",
    "neighborhood_code": "Neighborhood Code",
    "subdivision": "Subdivision",
    "zoning": "Zoning",
    "school_district": "School District",
    "elementary_school": "Elementary School",
    "middle_school": "Middle School",
    "high_school": "High School",
}
